### ISSUE TITLE
centos

### ISSUE THREAD

**Issue by arlolra** [joanpc/nginx_vhost_traffic#1]
hi,

this script doesn't seem to be working for me
both logtail and awk are installed, tested, working

if i stick a `print cn[$2]`
on line 81, i'm seeing 11, 22, 44, etc.
so data is being passed through

i have some questions about this
`$LOGTAIL ${ACCESS_LOG} $STATEFILE`

so you have logtail monitoring those two files
is that right?

what's supposed to the in the state file?
/var/lib/munin/plugin-state/nginx_vhost_traffic.state
cause mine's empty

thanks for you help

**Comment by joanpc** [comment]
Hi Alorla,

Sorry for the delay, I'm traveling. The state file is created by logtail to store the last line read from the log file i order to not re-parse the entire file, i don't know in what format.

Check the format of your nginx log file, you should use the format provided in the README file or you should specify the location of the $bytes_sent with the env.bparam  in the munin conf.

Tell me something :-)

cheers 

Joan.

**Comment by arlolra** [comment]
thanks for getting back to me joan
i think i'm getting closer

the `logtail` that you link to in your readme isn't the right one
it should be the following
http://www.logcheck.org/download.html

should line 38 have a `-` in front of `true`, like this:
`AGGREGATE=${aggregate:-true}`

also not that on line 28 of your script,
you have too many `i`s

now, if i login as `munin`
and execute the script, it spits out:

```
agregate: true
vhost1.value 0  
rest.value 825`
```

so at least that is working

but munin-cron doesn't seem to be
producing any data :(

arlo

**Comment by arlolra** [comment]
i checked the munin-node log files and logtail was complaining

changing from:
`$LOGTAIL ${ACCESS_LOG} $STATEFILE`

to this format fixed it:
`$LOGTAIL -f ${ACCESS_LOG} -o $STATEFILE`

its working!

**Comment by arlolra** [comment]
close

**Comment by joanpc** [comment]
Hi arlo, 
Thanks for pointing out that. It's weird cause the logtail debian version doesn't require the -o parameter but it understand it. I'll change that and the link to logtail.

Many thanks and enjoy your graphs :)

Joan.
